version: '2.3'

services:
  lit-llama-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: lit-llama-sandbox
    network_mode: "host"
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority
      - ./notebook:/app/notebook
      - ./checkpoints:/app/checkpoints
    privileged: yes
    command: "/bin/bash -c 'while :; do sleep 1; done'"
